name: Auto deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 171.244.33.91 }} #hostname of server
          username: ${{ root }} #username login to server
          password: ${{ gwDGAWJvOURA }} #password login to server
          port: ${{ 22 }} #port of server - often port is 22
          script: | # run with multiple script
            cd /aura
            cd edunftapi
            git pull
            printf "build docker iamge"
            ./deploy.sh